#Global configuration
global:
  #Directory for dumps
  path: "dump"
  #Directory for temporary files
  tmpPath: "tmp"
  #Shell (sh) executable location
  shExecutable: "sh"
  #tar executable location
  tarExecutable: "tar"
  #download: https://www.postgresql.org/download/
  pgdumpExecutable: "pg_dump"
  #download: https://mirror.truenetwork.ru/mariadb//mariadb-10.11.2/bintar-linux-systemd-x86_64/mariadb-10.11.2-linux-systemd-x86_64.tar.gz
  mysqldumpExecutable: "mysqldump"
  #download: https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.5.2.tgz
  mongodump5Executable: "/mongodb5/bin/mongodump"
  #download: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu1604-4.0.28.tgz
  mongodump4Executable: "/mongodb4/bin/mongodump"
  #download: https://github.com/FirebirdSQL/firebird/releases/tag/R2_5_9
  gbakExecutable: "/opt/firebird/bin/gbak"

#Send notifications to mattermost channel
notification:
  enabled: false
  url: "https://example.com/hooks/******"
  channel: "backup"
  username: "box"
  iconEmoji: ":package:"

dumps:
  #PostgreSQL
  - type: "postgres"
    name: "postgres_database"
    #connection parameters
    vars:
      host: "localhost"
      port: 5432
      username: "helloworld"
      password: "hunter2"
      dbname: "helloworld"
    #save daily dumps
    daily: true
    #keep daily dumps for days
    days: 14
    #save weekly dumps
    weekly: true
    #keep weekly dumps for weeks
    weeks: 8
    #save monthly dumps
    monthly: true
    #keep monthly dumps for months
    months: -1

  #MongoDB 5.0-4.0
  - type: "mongo"
    name: "mongodb_database"
    vars:
      host: "localhost"
      port: 27017
      username: "admin"
      password: "admin"
      authenticationDatabase: "admin"
      db: "helloworld"
    daily: true
    days: 14
    weekly: false
    monthly: false

  #MongoDB 4.0-2.6
  - type: "mongo_legacy"
    name: "mongodb_legacy_database"
    vars:
      host: "localhost"
      port: 27017
      username: "admin"
      password: "admin"
      authenticationDatabase: "admin"
      db: "helloworld"
    daily: true
    days: 10
    weekly: true
    weeks: 5

  #Firebird 2.5
  - type: "firebird_legacy"
    name: "firebird_database"
    vars:
      host: "localhost"
      username: "SYSDBA"
      password: "masterkey"
      db: "/sqlbase/database.fdb"
    daily: true
    days: 14

  #MySQL / MariaDB
  - type: "mysql"
    name: "mysql_database"
    vars:
      host: "localhost"
      port: 3306
      user: "helloworld"
      password: "hunter2"
      databases: "helloworld"

  #dump directory
  - type: "tar"
    name: "tar_archive"
    vars:
      path: "/directory/location"
      compress: "none|bzip2|gzip|lzma|xz"
    daily: true
    days: 14
